//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EinsteinGameClient1.EinsteinGameServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EinsteinGameDto", Namespace="")]
    [System.SerializableAttribute()]
    public partial class EinsteinGameDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] OutPutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] OutPut {
            get {
                return this.OutPutField;
            }
            set {
                if ((object.ReferenceEquals(this.OutPutField, value) != true)) {
                    this.OutPutField = value;
                    this.RaisePropertyChanged("OutPut");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EinsteinGameServiceReference.IEinsteinGameService")]
    public interface IEinsteinGameService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEinsteinGameService/RunGame", ReplyAction="http://tempuri.org/IEinsteinGameService/RunGameResponse")]
        EinsteinGameClient1.EinsteinGameServiceReference.EinsteinGameDto RunGame(int cheat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEinsteinGameService/RunGame", ReplyAction="http://tempuri.org/IEinsteinGameService/RunGameResponse")]
        System.Threading.Tasks.Task<EinsteinGameClient1.EinsteinGameServiceReference.EinsteinGameDto> RunGameAsync(int cheat);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEinsteinGameServiceChannel : EinsteinGameClient1.EinsteinGameServiceReference.IEinsteinGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EinsteinGameServiceClient : System.ServiceModel.ClientBase<EinsteinGameClient1.EinsteinGameServiceReference.IEinsteinGameService>, EinsteinGameClient1.EinsteinGameServiceReference.IEinsteinGameService {
        
        public EinsteinGameServiceClient() {
        }
        
        public EinsteinGameServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EinsteinGameServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EinsteinGameServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EinsteinGameServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EinsteinGameClient1.EinsteinGameServiceReference.EinsteinGameDto RunGame(int cheat) {
            return base.Channel.RunGame(cheat);
        }
        
        public System.Threading.Tasks.Task<EinsteinGameClient1.EinsteinGameServiceReference.EinsteinGameDto> RunGameAsync(int cheat) {
            return base.Channel.RunGameAsync(cheat);
        }
    }
}
